<?php

namespace Database\Seeders;

use App\Models\Front;
use Illuminate\Database\Seeder;

class FrontSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // menu
        $menu = array(
            array(
                'title' => 'Dashboard HR',
                'route' => 'dashboard_hr',
                'parent_id' => null,
                'is_parent' => false,
                'is_active' => true,
                'group' => 1,
            ),
            array(
                'title' => 'Dashboard OAsys',
                'route' => 'dashboard_oasys',
                'is_parent' => false,
                'parent_id' => null,
                'is_active' => true,
                'group' => 1,
            ),
            array(
                'title' => 'Module',
                'route' => 'admin_module',
                'is_parent' => false,
                'parent_id' => null,
                'is_active' => true,
                'group' => 2,
            ),
            array(
                'title' => 'Role',
                'route' => 'admin_role',
                'parent_id' => null,
                'is_parent' => false,
                'is_active' => true,
                'group' => 2,
            ),
            array(
                'title' => 'User',
                'route' => 'admin_user',
                'parent_id' => null,
                'is_parent' => false,
                'is_active' => true,
                'group' => 2,
            ),
            array(
                'title' => 'Advance',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Approval Advance',
                'route' => 'approval_advance',
                'parent_id' => 6,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Report Advance',
                'route' => 'report_advance',
                'parent_id' => 6,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Request Advance',
                'route' => 'request_advance',
                'parent_id' => 6,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'IT',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'IT Approval',
                'route' => 'it_approval',
                'parent_id' => 10,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'IT Report',
                'route' => 'it_report',
                'parent_id' => 10,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'IT Request',
                'route' => 'it_request',
                'parent_id' => 10,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'MMF',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'MMF Approval',
                'route' => 'mmf_approval',
                'parent_id' => 13,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'MMF Report',
                'route' => 'mmf_report',
                'parent_id' => 13,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'MMF Request',
                'route' => 'mmf_request',
                'parent_id' => 13,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Payment',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Payment Approval',
                'route' => 'payment_approval',
                'parent_id' => 16,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Payment Report',
                'route' => 'payment_report',
                'parent_id' => 16,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Payment Request',
                'route' => 'payment_request',
                'parent_id' => 16,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'PH Coverage',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'PH Approval',
                'route' => 'ph_approval',
                'parent_id' => 16,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'PH Report',
                'route' => 'ph_report',
                'parent_id' => 16,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'PH Request',
                'route' => 'ph_request',
                'parent_id' => 16,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'RFC',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'RFC Approval',
                'route' => 'rfc_approval',
                'parent_id' => 19,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'RFC Report',
                'route' => 'rfc_report',
                'parent_id' => 19,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'RFC Request',
                'route' => 'rfc_request',
                'parent_id' => 19,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'SKPL',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'SKPL Approval',
                'route' => 'skpl_approval',
                'parent_id' => 22,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'SKPL Report',
                'route' => 'skpl_report',
                'parent_id' => 22,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'SKPL Request',
                'route' => 'skpl_request',
                'parent_id' => 19,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Travel',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Travel Approval',
                'route' => 'travel_approval',
                'parent_id' => 25,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Travel Report',
                'route' => 'travel_report',
                'parent_id' => 22,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Travel Request',
                'route' => 'travel_request',
                'parent_id' => 19,
                'is_parent' => false,
                'is_active' => true,
                'group' => 3,
            ),
            array(
                'title' => 'Approver',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 4,
            ),
            array(
                'title' => 'Balance',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 4,
            ),
            array(
                'title' => 'Company',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 4,
            ),
            array(
                'title' => 'Department',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 4,
            ),
            array(
                'title' => 'Designation',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 4,
            ),
            array(
                'title' => 'Division',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 4,
            ),
            array(
                'title' => 'Holiday',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 4,
            ),
            array(
                'title' => 'Internal Hiring',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 4,
            ),
            array(
                'title' => 'RFC Master',
                'route' => null,
                'parent_id' => null,
                'is_parent' => true,
                'is_active' => true,
                'group' => 4,
            ),
            array(
                'title' => 'Activity',
                'route' => 'rfc_activity',
                'parent_id' => 22,
                'is_parent' => false,
                'is_active' => true,
                'group' => 4,
            ),
            array(
                'title' => 'Contractor',
                'route' => 'rfc_contractor',
                'parent_id' => 22,
                'is_parent' => false,
                'is_active' => true,
                'group' => 4,
            ),
            array(
                'title' => 'SK',
                'route' => 'rfc_sk',
                'parent_id' => 22,
                'is_parent' => false,
                'is_active' => true,
                'group' => 4,
            ),
        );

        foreach ($menu as $item) {
            Front::create($item);
        }
    }
}